name: Update JOE Data

on:
  schedule:
    # Run at 5pm EST every Friday (22:00 UTC, day 5)
    - cron: '0 22 * * 5'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Install dependencies
      run: |
        pip install selenium pandas openpyxl matplotlib
        pip install webdriver-manager

    - name: Download existing data file
      run: |
        mkdir -p docs
        echo "Downloading existing joe_data.json from GitHub Pages..."
        curl -sL https://davidvandijcke.com/joe_tracker/joe_data.json -o docs/joe_data.json || echo '{"metadata":{"total_postings":0},"sections":{}}' > docs/joe_data.json
        echo "Existing data file size: $(wc -c < docs/joe_data.json) bytes"

    - name: Run scraper
      run: |
        python joe_working_scraper.py --years 1 --headless
    
    - name: Generate static site
      run: |
        python generate_static_site.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update JOE data" && git push)
