name: Update JOE Data

on:
  schedule:
    # Run at 5pm EST every Friday (22:00 UTC, day 5)
    - cron: '0 22 * * 5'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Install dependencies
      run: |
        pip install selenium pandas openpyxl matplotlib
        pip install webdriver-manager
    
    - name: Run scraper
      run: |
        python joe_working_scraper.py --years 1 --headless
    
    - name: Generate static site
      run: |
        python generate_static_site.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

        # Fetch latest changes first
        git fetch origin main

        # Add all changes
        git add -A

        # Check if there are changes
        if ! git diff --quiet || ! git diff --staged --quiet; then
          git commit -m "Auto-update JOE data"

          # Stash any unstaged changes
          git stash --include-untracked

          git rebase origin/main
          git push origin HEAD:main

          # Clean up stash
          git stash drop || true
        else
          echo "No changes to commit"
        fi
