name: Update JOE Data

on:
  schedule:
    # Run at 5pm EST every Friday (22:00 UTC, day 5)
    - cron: '0 22 * * 5'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to commit and push changes

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Install dependencies
      run: |
        pip install selenium pandas openpyxl matplotlib
        pip install webdriver-manager

    - name: Create directory structure
      run: |
        mkdir -p joe_data/scraped/temp
        mkdir -p docs

    - name: Run scraper
      run: |
        # Downloads current year with ALL sections in one file
        python joe_working_scraper.py --years 1 --headless
    
    - name: Generate static site
      run: |
        python generate_static_site.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update JOE data" && git push)
